Rewrite to use commands instead of options

diff --git a/bin/secret b/bin/secret
--- a/bin/secret
+++ b/bin/secret
@@ -1,6 +1,7 @@
 #! /usr/bin/env bash
 set -e
 
+BN=$(basename "$0")
 secretDir="$GOODIES_SECRETS_DIR"
 
 if [[ -z "$secretDir" ]]; then
@@ -13,58 +14,74 @@ usage() {
     cat <<EOF
 Manage secrets stored encrypted in files.
 
-Usage: $(basename $0) [options] [args]
-options:
-  --get: Print a secret. Default if no options is given
-  --delete: Delete a secret
-  --create: Create a new secret. The value is randomly generated
-  --store: Store a new secret. The value is read from stdin
+Usage: ${BN} cmd [options] [args] 
+
+Commands:
 EOF
-    
+    sed -n "s/\(^.*\)().*#CMD\\s/\t\1:\t/p;" < "$0"
 }
 
-cmd=get
-needName=1
-while [[ "$1" = -* ]]; do
-    case "$1" in
-        (--create|--delete|--get|--store)
-            cmd=${1:2}
-            ;;
-        (--print|--list)
-            cmd=${1:2}
-            needName=0
-            ;;
-        (--help)
-            usage
-            exit 0
-            ;;
-        (--)
-            break
-            ;;
-        (*)
-            echo "Illegal option: $1"
-            exit 2
-    esac
-    shift
-done
+cmd="$1"
+[[ -z "$cmd" ]] && echo "Missing command" && exit 1
+shift
+needNameArg=1
+case "$cmd" in
+    (create|store)
+        optionString=f
+        ;;
+    (delete|get)
+        ;;
+    (print|list)
+        needNameArg=0
+        ;;
+    (help)
+        usage
+        exit 0
+        ;;
+    (*)
+        echo "Illegal command: $1"
+        exit 2
+esac
+# while [[ "$1" = -* ]]; do
+#     shift
+# done
 
+if [[ -n "$optionString" ]]; then
+    t=$(getopt -u -o "$optionString" -n ${BN} -- "$@")
+    set -- $t
+    while true; do
+        case "$1" in
+            (-f)
+                force=1
+                ;;
+            (--)
+                shift
+                break
+                ;;
+            (*)
+                echo "Internal error"
+                exit 5
+        esac
+        shift
+    done
+fi
 name="$1"
-[[ -z "$name" && $needName = 1 ]] && echo "Missing name" && exit 1
+[[ -z "$name" && $needNameArg = 1 ]] && echo "Missing name" && exit 1
 file="$secretDir/$1.gpg"
 
 _generate() {
     cat /dev/urandom | tr -dc 'A-z0-9!@#$%^&*()-=+' | head -c$length
 }
 
-create() {
+create() { #CMD Create a new secret
     _generate | store
 }
 
-delete() {
+delete() { #CMD Delete a secret
     rm -f "$file"
 }
 
-get() {
+get() { #CMD Get a secret
     if [[ -f "$file" ]]; then
         gpg --quiet --batch < "$file"
     else
@@ -73,8 +90,8 @@ get() {
     fi
 }
 
-store() {
-    if [[ -f "$file" ]]; then
+store() { #CMD Read stdin and store it as a secret
+    if [[ -f "$file" && "$force" -ne 1 ]]; then
         echo "Secret exist"
         exit 7
     else
@@ -82,11 +99,11 @@ store() {
     fi    
 }
 
-print() {
+print() { #CMD Generate a 'secret' and print it. It is not stored
     _generate
 }
 
-list() {
+list() { #CMD List all secrets
     ls -1 "$secretDir" | sed 's/\..*//'
 }
 
